"""add region fields to rpg_lore

Revision ID: 0c0240f38440
Revises: 1b68e727b117
Create Date: 2026-06-28 16:20:35.263501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c0240f38440'
down_revision: Union[str, Sequence[str], None] = '1b68e727b117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "rpg_lore",
        sa.Column(
            "is_region",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )

    op.add_column(
        "rpg_lore",
        sa.Column(
            "region_type",
            sa.String(length=50),
            nullable=True,
        ),
    )

    # remove o default do banco após preencher os registros antigos
    op.alter_column(
        "rpg_lore",
        "is_region",
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpg_lore', 'region_type')
    op.drop_column('rpg_lore', 'is_region')
    # ### end Alembic commands ###
