"""add timeline characters

Revision ID: 18ae7f7ee50b
Revises: d007ec6bd911
Create Date: 2026-06-10 01:06:05.051990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ae7f7ee50b'
down_revision: Union[str, Sequence[str], None] = 'd007ec6bd911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_timeline_characters',
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['rpg_timeline.id'], ),
    sa.PrimaryKeyConstraint('timeline_id', 'character_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpg_timeline_characters')
    # ### end Alembic commands ###
