"""add rpg_id and turn_id to notifications

Revision ID: 35815c98f26f
Revises: fe5c50cea33a
Create Date: 2026-04-23 15:44:27.921167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35815c98f26f'
down_revision: Union[str, Sequence[str], None] = 'fe5c50cea33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('rpg_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('turn_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'turn_id')
    op.drop_column('notifications', 'rpg_id')
    # ### end Alembic commands ###
