"""add timeline factions

Revision ID: 3fe84ab1dfa4
Revises: 88377bd597c7
Create Date: 2026-06-14 04:04:58.589894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe84ab1dfa4'
down_revision: Union[str, Sequence[str], None] = '88377bd597c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_timeline_factions',
    sa.Column('timeline_id', sa.Integer(), nullable=False),
    sa.Column('faction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faction_id'], ['rpg_factions.id'], ),
    sa.ForeignKeyConstraint(['timeline_id'], ['rpg_timeline.id'], ),
    sa.PrimaryKeyConstraint('timeline_id', 'faction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpg_timeline_factions')
    # ### end Alembic commands ###
