"""create rpg factions

Revision ID: 4e3198787ddc
Revises: 18ae7f7ee50b
Create Date: 2026-06-13 16:49:01.876590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3198787ddc'
down_revision: Union[str, Sequence[str], None] = '18ae7f7ee50b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rpg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpg_id'], ['rpgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpg_factions_id'), 'rpg_factions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpg_factions_id'), table_name='rpg_factions')
    op.drop_table('rpg_factions')
    # ### end Alembic commands ###
