"""add world_map to rpgs

Revision ID: 5fb8867f22e2
Revises: facdbc844e75
Create Date: 2026-05-08 02:37:25.734788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb8867f22e2'
down_revision: Union[str, Sequence[str], None] = 'facdbc844e75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpgs', sa.Column('world_map', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpgs', 'world_map')
    # ### end Alembic commands ###
