"""add lore system

Revision ID: 696278ac899a
Revises: 8fe823e18eb9
Create Date: 2026-03-21 18:53:48.519082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696278ac899a'
down_revision: Union[str, Sequence[str], None] = '8fe823e18eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpg_lore', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('rpg_lore', sa.Column('is_suggestion', sa.Boolean(), nullable=True))
    op.add_column('rpgs', sa.Column('allow_lore_suggestions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpgs', 'allow_lore_suggestions')
    op.drop_column('rpg_lore', 'is_suggestion')
    op.drop_column('rpg_lore', 'is_approved')
    # ### end Alembic commands ###
