"""add banner url to rpgs

Revision ID: 6a1b9319dc00
Revises: 862b45496a1a
Create Date: 2026-05-27 20:46:04.253940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a1b9319dc00'
down_revision: Union[str, Sequence[str], None] = '862b45496a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpgs', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpgs', 'banner_url')
    # ### end Alembic commands ###
