"""add rpg configuration fields

Revision ID: 7cabfe714c3b
Revises: 6d7487661690
Create Date: 2026-03-05 01:25:26.089178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cabfe714c3b'
down_revision: Union[str, Sequence[str], None] = '6d7487661690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpgs', sa.Column('has_gm', sa.Boolean(), nullable=True))
    op.add_column('rpgs', sa.Column('allow_chat', sa.Boolean(), nullable=True))
    op.add_column('rpgs', sa.Column('allow_character_sheets', sa.Boolean(), nullable=True))
    op.add_column('rpgs', sa.Column('allow_join_requests', sa.Boolean(), nullable=True))
    op.add_column('rpgs', sa.Column('turn_mode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpgs', 'turn_mode')
    op.drop_column('rpgs', 'allow_join_requests')
    op.drop_column('rpgs', 'allow_character_sheets')
    op.drop_column('rpgs', 'allow_chat')
    op.drop_column('rpgs', 'has_gm')
    # ### end Alembic commands ###
