"""create rpg map regions

Revision ID: 862b45496a1a
Revises: ccd21ee3e7b0
Create Date: 2026-05-27 02:32:38.680305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862b45496a1a'
down_revision: Union[str, Sequence[str], None] = 'ccd21ee3e7b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_map_regions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpg_id', sa.Integer(), nullable=False),
    sa.Column('lore_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['lore_id'], ['rpg_lore.id'], ),
    sa.ForeignKeyConstraint(['rpg_id'], ['rpgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpg_map_regions_id'), 'rpg_map_regions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpg_map_regions_id'), table_name='rpg_map_regions')
    op.drop_table('rpg_map_regions')
    # ### end Alembic commands ###
