"""add faction to characters

Revision ID: 88377bd597c7
Revises: 4e3198787ddc
Create Date: 2026-06-13 17:01:25.259386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88377bd597c7'
down_revision: Union[str, Sequence[str], None] = '4e3198787ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('faction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'characters', 'rpg_factions', ['faction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_column('characters', 'faction_id')
    # ### end Alembic commands ###
