"""create rpg turns table

Revision ID: 8e5b52dd1209
Revises: 7cabfe714c3b
Create Date: 2026-03-05 11:12:47.837065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5b52dd1209'
down_revision: Union[str, Sequence[str], None] = '7cabfe714c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpg_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_id'], ['rpgs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpg_turns_id'), 'rpg_turns', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpg_turns_id'), table_name='rpg_turns')
    op.drop_table('rpg_turns')
    # ### end Alembic commands ###
