"""add performance indexes

Revision ID: 8fe823e18eb9
Revises: c731525a2427
Create Date: 2026-03-15 16:09:49.536192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe823e18eb9'
down_revision: Union[str, Sequence[str], None] = 'c731525a2427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_character_rpg_user', 'characters', ['rpg_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_characters_rpg_id'), 'characters', ['rpg_id'], unique=False)
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_index('idx_participant_user_rpg', 'rpg_participants', ['user_id', 'rpg_id'], unique=False)
    op.create_index(op.f('ix_rpg_participants_rpg_id'), 'rpg_participants', ['rpg_id'], unique=False)
    op.create_index(op.f('ix_rpg_participants_user_id'), 'rpg_participants', ['user_id'], unique=False)
    op.create_index('idx_turn_rpg_created', 'rpg_turns', ['rpg_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_rpg_turns_created_at'), 'rpg_turns', ['created_at'], unique=False)
    op.create_index(op.f('ix_rpg_turns_reply_to_turn_id'), 'rpg_turns', ['reply_to_turn_id'], unique=False)
    op.create_index(op.f('ix_rpg_turns_rpg_id'), 'rpg_turns', ['rpg_id'], unique=False)
    op.create_index(op.f('ix_rpg_turns_user_id'), 'rpg_turns', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpg_turns_user_id'), table_name='rpg_turns')
    op.drop_index(op.f('ix_rpg_turns_rpg_id'), table_name='rpg_turns')
    op.drop_index(op.f('ix_rpg_turns_reply_to_turn_id'), table_name='rpg_turns')
    op.drop_index(op.f('ix_rpg_turns_created_at'), table_name='rpg_turns')
    op.drop_index('idx_turn_rpg_created', table_name='rpg_turns')
    op.drop_index(op.f('ix_rpg_participants_user_id'), table_name='rpg_participants')
    op.drop_index(op.f('ix_rpg_participants_rpg_id'), table_name='rpg_participants')
    op.drop_index('idx_participant_user_rpg', table_name='rpg_participants')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_rpg_id'), table_name='characters')
    op.drop_index('idx_character_rpg_user', table_name='characters')
    # ### end Alembic commands ###
