"""add dynamic character sheets

Revision ID: 908b9835da73
Revises: f148e6539814
Create Date: 2026-03-15 02:30:34.572625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '908b9835da73'
down_revision: Union[str, Sequence[str], None] = 'f148e6539814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_sheet_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpg_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['rpg_id'], ['rpgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpg_sheet_fields_id'), 'rpg_sheet_fields', ['id'], unique=False)
    op.create_table('character_sheet_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['rpg_sheet_fields.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_sheet_values_id'), 'character_sheet_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_sheet_values_id'), table_name='character_sheet_values')
    op.drop_table('character_sheet_values')
    op.drop_index(op.f('ix_rpg_sheet_fields_id'), table_name='rpg_sheet_fields')
    op.drop_table('rpg_sheet_fields')
    # ### end Alembic commands ###
