"""create region places

Revision ID: 9abb65525baf
Revises: 3fe84ab1dfa4
Create Date: 2026-06-17 01:12:41.537579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abb65525baf'
down_revision: Union[str, Sequence[str], None] = '3fe84ab1dfa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lore_id'], ['rpg_lore.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_places_id'), 'region_places', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_places_id'), table_name='region_places')
    op.drop_table('region_places')
    # ### end Alembic commands ###
