"""add rpg settings

Revision ID: a5ab566f6de4
Revises: c4b962065598
Create Date: 2026-06-23 19:06:12.316113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ab566f6de4'
down_revision: Union[str, Sequence[str], None] = 'c4b962065598'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rpg_id', sa.Integer(), nullable=False),
    sa.Column('use_ai_assistant', sa.Boolean(), nullable=True),
    sa.Column('use_ai_narrator', sa.Boolean(), nullable=True),
    sa.Column('use_ai_events', sa.Boolean(), nullable=True),
    sa.Column('use_ai_npcs', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rpg_id'], ['rpgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rpg_id')
    )
    op.create_index(op.f('ix_rpg_settings_id'), 'rpg_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpg_settings_id'), table_name='rpg_settings')
    op.drop_table('rpg_settings')
    # ### end Alembic commands ###
