"""add pinned notes

Revision ID: a66ec58173f5
Revises: 3cf4ca779944
Create Date: 2026-05-30 01:34:27.508863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66ec58173f5'
down_revision: Union[str, Sequence[str], None] = '3cf4ca779944'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'rpg_notes',
    sa.Column(
        'is_pinned',
        sa.Boolean(),
        nullable=False,
        server_default=sa.false(),
    )
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpg_notes', 'is_pinned')
    # ### end Alembic commands ###
