"""add turn replies and mentions

Revision ID: b3ad36b8f3ab
Revises: 86af5392f8a7
Create Date: 2026-03-06 03:32:11.120551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3ad36b8f3ab'
down_revision: Union[str, Sequence[str], None] = '86af5392f8a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turn_mentions',
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['rpg_participants.id'], ),
    sa.ForeignKeyConstraint(['turn_id'], ['rpg_turns.id'], )
    )
    op.add_column('rpg_turns', sa.Column('reply_to_turn_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rpg_turns', 'rpg_turns', ['reply_to_turn_id'], ['id'])
    op.add_column('rpgs', sa.Column('allow_free_turns', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpgs', 'allow_free_turns')
    op.drop_constraint(None, 'rpg_turns', type_='foreignkey')
    op.drop_column('rpg_turns', 'reply_to_turn_id')
    op.drop_table('turn_mentions')
    # ### end Alembic commands ###
