"""create rpg lore relations table

Revision ID: b3e8d1202e9f
Revises: bbb8b87b052a
Create Date: 2026-06-02 03:54:53.453492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e8d1202e9f'
down_revision: Union[str, Sequence[str], None] = 'bbb8b87b052a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_lore_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_lore_id', sa.Integer(), nullable=False),
    sa.Column('target_lore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_lore_id'], ['rpg_lore.id'], ),
    sa.ForeignKeyConstraint(['target_lore_id'], ['rpg_lore.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_lore_id', 'target_lore_id', name='uq_lore_relation')
    )
    op.create_index(op.f('ix_rpg_lore_relations_id'), 'rpg_lore_relations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpg_lore_relations_id'), table_name='rpg_lore_relations')
    op.drop_table('rpg_lore_relations')
    # ### end Alembic commands ###
