"""add lore to timeline events

Revision ID: ba39802c6413
Revises: 9f0c362546f1
Create Date: 2026-05-31 21:14:31.536557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba39802c6413'
down_revision: Union[str, Sequence[str], None] = '9f0c362546f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpg_timeline', sa.Column('lore_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rpg_timeline', 'rpg_lore', ['lore_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rpg_timeline', type_='foreignkey')
    op.drop_column('rpg_timeline', 'lore_id')
    # ### end Alembic commands ###
