"""add search indexes

Revision ID: c0195d90904b
Revises: 696278ac899a
Create Date: 2026-03-21 19:20:24.741675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0195d90904b'
down_revision: Union[str, Sequence[str], None] = '696278ac899a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_index(op.f('ix_rpg_lore_title'), 'rpg_lore', ['title'], unique=False)
    op.create_index(op.f('ix_rpgs_name'), 'rpgs', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rpgs_name'), table_name='rpgs')
    op.drop_index(op.f('ix_rpg_lore_title'), table_name='rpg_lore')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    # ### end Alembic commands ###
