"""create scene locations

Revision ID: c4b962065598
Revises: d7019b9c6b20
Create Date: 2026-06-19 02:53:28.720248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4b962065598'
down_revision: Union[str, Sequence[str], None] = 'd7019b9c6b20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pos_x', sa.Integer(), nullable=True),
    sa.Column('pos_y', sa.Integer(), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('target_scene_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['region_scenes.id'], ),
    sa.ForeignKeyConstraint(['target_scene_id'], ['region_scenes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_locations_id'), 'scene_locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_locations_id'), table_name='scene_locations')
    op.drop_table('scene_locations')
    # ### end Alembic commands ###
