"""add category to rpg sheet fields

Revision ID: ccd21ee3e7b0
Revises: ec3d8cb97e13
Create Date: 2026-05-27 02:01:01.056610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ccd21ee3e7b0'
down_revision: Union[str, Sequence[str], None] = 'ec3d8cb97e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpg_map_regions')
    op.alter_column('rpg_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('rpg_messages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.add_column('rpg_sheet_fields', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpg_sheet_fields', 'category')
    op.alter_column('rpg_messages', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('rpg_messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('rpg_map_regions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rpg_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('lore_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('pos_x', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pos_y', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['lore_id'], ['rpg_lore.id'], name=op.f('rpg_map_regions_lore_id_fkey')),
    sa.ForeignKeyConstraint(['rpg_id'], ['rpgs.id'], name=op.f('rpg_map_regions_rpg_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rpg_map_regions_pkey'))
    )
    # ### end Alembic commands ###
