"""add turn to timeline events

Revision ID: cebf999e676b
Revises: b3e8d1202e9f
Create Date: 2026-06-04 03:23:19.384784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebf999e676b'
down_revision: Union[str, Sequence[str], None] = 'b3e8d1202e9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpg_timeline', sa.Column('turn_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rpg_timeline', 'rpg_turns', ['turn_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rpg_timeline', type_='foreignkey')
    op.drop_column('rpg_timeline', 'turn_id')
    # ### end Alembic commands ###
