"""create timeline categories

Revision ID: d007ec6bd911
Revises: af84f6b1642e
Create Date: 2026-06-05 02:01:27.322965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd007ec6bd911'
down_revision: Union[str, Sequence[str], None] = 'af84f6b1642e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_timeline_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rpg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpg_id'], ['rpgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpg_timeline_categories_id'), 'rpg_timeline_categories', ['id'], unique=False)
    op.add_column('rpg_timeline', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rpg_timeline', 'rpg_timeline_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rpg_timeline', type_='foreignkey')
    op.drop_column('rpg_timeline', 'category_id')
    op.drop_index(op.f('ix_rpg_timeline_categories_id'), table_name='rpg_timeline_categories')
    op.drop_table('rpg_timeline_categories')
    # ### end Alembic commands ###
