"""create region scenes

Revision ID: d7019b9c6b20
Revises: da71416d98bd
Create Date: 2026-06-18 02:52:16.533135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7019b9c6b20'
down_revision: Union[str, Sequence[str], None] = 'da71416d98bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('lore_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lore_id'], ['rpg_lore.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_region_scenes_id'), 'region_scenes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_region_scenes_id'), table_name='region_scenes')
    op.drop_table('region_scenes')
    # ### end Alembic commands ###
