"""add visual description to lore

Revision ID: da71416d98bd
Revises: 9abb65525baf
Create Date: 2026-06-17 19:43:17.642117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da71416d98bd'
down_revision: Union[str, Sequence[str], None] = '9abb65525baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rpg_lore', sa.Column('visual_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpg_lore', 'visual_description')
    # ### end Alembic commands ###
