"""add lore categories

Revision ID: facdbc844e75
Revises: a1eb178b08f4
Create Date: 2026-05-03 16:06:08.441240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'facdbc844e75'
down_revision: Union[str, Sequence[str], None] = 'a1eb178b08f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpg_lore_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('rpg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rpg_id'], ['rpgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rpg_lore_categories_id'), 'rpg_lore_categories', ['id'], unique=False)
    op.drop_column('notifications', 'turn_id')
    op.drop_column('notifications', 'rpg_id')
    op.alter_column('rpg_lore', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rpg_lore', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rpg_lore', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rpg_lore', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('notifications', sa.Column('rpg_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('notifications', sa.Column('turn_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_rpg_lore_categories_id'), table_name='rpg_lore_categories')
    op.drop_table('rpg_lore_categories')
    # ### end Alembic commands ###
