"""add mentioned_characters

Revision ID: fe5c50cea33a
Revises: ef8acdf42387
Create Date: 2026-04-18 22:53:37.019098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe5c50cea33a'
down_revision: Union[str, Sequence[str], None] = 'ef8acdf42387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_sheet_values', 'value',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_rpg_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_user_id'), table_name='characters')
    op.add_column('rpg_turns', sa.Column('mentioned_characters', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('rpg_turns_character_id_fkey'), 'rpg_turns', type_='foreignkey')
    op.create_foreign_key(None, 'rpg_turns', 'characters', ['character_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rpg_turns', type_='foreignkey')
    op.create_foreign_key(op.f('rpg_turns_character_id_fkey'), 'rpg_turns', 'characters', ['character_id'], ['id'], ondelete='SET NULL')
    op.drop_column('rpg_turns', 'mentioned_characters')
    op.create_index(op.f('ix_characters_user_id'), 'characters', ['user_id'], unique=False)
    op.create_index(op.f('ix_characters_rpg_id'), 'characters', ['rpg_id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.alter_column('character_sheet_values', 'value',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
